services:
  postgres:
    container_name: django_postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: django_db
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data: